from machine import Pin, PWM, I2C
from time import sleep


class Motor:
    def __init__(self, direction_pin, pwm_pin, forward_logic):
        self.DIR = Pin(direction_pin, Pin.OUT)
        self.PWM = PWM(Pin(pwm_pin, Pin.OUT), freq=1000, duty=0)
        self.PWM.deinit()
        self.PWM.init()
        self.PWM.duty(0)
        self.forward_logic = forward_logic

    def set(self, speed):
        speed = max(-100, min(100, speed))
        self.DIR.value(self.forward_logic if speed > 0 else (1 - self.forward_logic))
        self.PWM.duty(int(abs(speed) / 100.0 * 1023.0))


M1 = Motor(18, 19, 1)
M2 = Motor(23, 2, 0)


class Servo:
    def __init__(self, pin):
        self.pin = PWM(Pin(pin, Pin.OUT), freq=50, duty=0)
        self.pin.deinit()
        self.pin.init()
        self.pin.freq(50)
        self.pin.duty(0)

    def angle(self, value):
        value = max(0, min(180, value))
        self.pin.duty(int(25.57 + ((value / 180.0) * 102.3)))

    def stop(self):
        self.pin.duty(0)


SV1 = Servo(4)
SV2 = Servo(15)

ADS7828_ADDR = 0x4A


def ADC(ch):
    i2c = I2C(0, scl=Pin(21), sda=Pin(22), freq=100000)
    i2c.writeto(
        ADS7828_ADDR,
        bytes([((0, 4, 1, 5, 2, 6, 3, 7)[ch] << 4) | 0x8C])
    )
    high, low = i2c.readfrom(ADS7828_ADDR, 2)
    return ((high << 8) | low) & 0x0FFF


_movement_speed = 100
_line_left_port = 1
_line_right_port = 2
_threshold_left = 0
_threshold_right = 0
_intersection_forward_time = 0.5


def _drive(action, speed):
    if action == "FORWARD":
        M1.set(speed)
        M2.set(speed)
    elif action == "BACKWARD":
        M1.set(-speed)
        M2.set(-speed)
    elif action == "TURN_LEFT":
        M1.set(0)
        M2.set(speed)
    elif action == "TURN_RIGHT":
        M1.set(speed)
        M2.set(0)
    elif action == "SPIN_LEFT":
        M1.set(-speed)
        M2.set(speed)
    elif action == "SPIN_RIGHT":
        M1.set(speed)
        M2.set(-speed)
    else:
        M1.set(0)
        M2.set(0)


def move(action, speed):
    global _movement_speed

    speed = abs(max(-100, min(100, speed)))
    _movement_speed = speed
    _drive(action, speed)


def uturn(direction, speed=None):
    # Compatibility with code generated by iBIT extension 1.1.4.
    if speed is None:
        speed = direction
        direction = "LEFT"

    speed = abs(max(-100, min(100, speed)))
    if direction == "RIGHT":
        action = "SPIN_RIGHT"
        sensor_channel = _line_right_port
        reference = _threshold_right
    else:
        action = "SPIN_LEFT"
        sensor_channel = _line_left_port
        reference = _threshold_left

    _drive(action, speed)

    if _line_detected(sensor_channel, reference):
        while _line_detected(sensor_channel, reference):
            sleep(0.001)

    while not _line_detected(sensor_channel, reference):
        sleep(0.001)

    _drive("STOP", 0)


def set_line_sensor_ports(left=1, right=2):
    global _line_left_port, _line_right_port
    _line_left_port = max(0, min(7, int(left)))
    _line_right_port = max(0, min(7, int(right)))


def set_threshold_left(value):
    global _threshold_left
    _threshold_left = value


def set_threshold_right(value):
    global _threshold_right
    _threshold_right = value


def set_ref_l(value):
    # Compatibility with code generated by iBIT extension 1.1.13 and earlier.
    set_threshold_left(value)


def set_ref_r(value):
    # Compatibility with code generated by iBIT extension 1.1.13 and earlier.
    set_threshold_right(value)


def set_intersection_forward_time(seconds):
    global _intersection_forward_time
    _intersection_forward_time = max(0, seconds)


def _line_detected(channel, reference):
    return ADC(channel) <= reference


def _wait_for_intersection():
    while not (
        _line_detected(_line_left_port, _threshold_left)
        and _line_detected(_line_right_port, _threshold_right)
    ):
        sleep(0.001)


def _set_motor_speeds(speed_left, speed_right):
    M1.set(speed_left)
    M2.set(speed_right)


def _get_line_speeds(speed_left, speed_right):
    if speed_left is None:
        speed_left = _movement_speed
    else:
        speed_left = abs(max(-100, min(100, speed_left)))

    if speed_right is None:
        speed_right = speed_left
    else:
        speed_right = abs(max(-100, min(100, speed_right)))

    return speed_left, speed_right


def _follow_line_until_intersection(speed_left, speed_right):
    while True:
        left_detected = _line_detected(_line_left_port, _threshold_left)
        right_detected = _line_detected(_line_right_port, _threshold_right)

        if left_detected and right_detected:
            return

        if not left_detected and not right_detected:
            _set_motor_speeds(speed_left, speed_right)
        elif left_detected:
            _drive("TURN_LEFT", speed_left)
        else:
            _drive("TURN_RIGHT", speed_right)

        sleep(0.001)


def intersection(action, forward_time=None, speed=None, speed_right=None):
    if forward_time is None:
        forward_time = _intersection_forward_time
    else:
        forward_time = max(0, forward_time)

    speed_left, speed_right = _get_line_speeds(speed, speed_right)

    _follow_line_until_intersection(speed_left, speed_right)
    _set_motor_speeds(speed_left, speed_right)
    sleep(forward_time)

    if action == "CROSS":
        return

    if action == "STOP":
        _drive("STOP", 0)
        return

    if action == "TURN_LEFT":
        _drive("SPIN_LEFT", speed_left)
        while not _line_detected(_line_left_port, _threshold_left):
            sleep(0.001)
    elif action == "TURN_RIGHT":
        _drive("SPIN_RIGHT", speed_right)
        while not _line_detected(_line_right_port, _threshold_right):
            sleep(0.001)

    _drive("STOP", 0)


def intersection_stop(speed=None, speed_right=None):
    speed_left, speed_right = _get_line_speeds(speed, speed_right)
    _follow_line_until_intersection(speed_left, speed_right)
    _drive("STOP", 0)


class Gripper:
    def __init__(self):
        self.enabled = False
        self.grip_servo = SV1
        self.lift_servo = SV2
        self.positions = {
            "GRAB": 80,
            "RELEASE": 25,
            "UP": 10,
            "DOWN": 110
        }
        self.settle_time = 0.3

    def enable(self, enabled):
        self.enabled = bool(enabled)
        if not self.enabled:
            SV1.stop()
            SV2.stop()

    def set_ports(self, layout):
        if layout == "SWAPPED":
            self.grip_servo = SV2
            self.lift_servo = SV1
        else:
            self.grip_servo = SV1
            self.lift_servo = SV2

    def set_degree(self, position, degree):
        if position in self.positions:
            self.positions[position] = max(0, min(180, degree))

    def _move_to(self, position):
        if not self.enabled or position not in self.positions:
            return

        if position == "GRAB" or position == "RELEASE":
            self.grip_servo.angle(self.positions[position])
        else:
            self.lift_servo.angle(self.positions[position])
        sleep(self.settle_time)

    def control(self, action):
        if action == "PICK_UP":
            self._move_to("GRAB")
            self._move_to("UP")
        elif action == "PLACE_DOWN":
            self._move_to("DOWN")
            self._move_to("RELEASE")
        else:
            self._move_to(action)

    def home(self):
        self._move_to("RELEASE")
        self._move_to("UP")

    def stop(self):
        SV1.stop()
        SV2.stop()


GripperX = Gripper()
