from machine import Pin, PWM, I2C
from time import sleep


class Motor:
    def __init__(self, direction_pin, pwm_pin, forward_logic):
        self.DIR = Pin(direction_pin, Pin.OUT)
        self.PWM = PWM(Pin(pwm_pin, Pin.OUT), freq=1000, duty=0)
        self.PWM.deinit()
        self.PWM.init()
        self.PWM.duty(0)
        self.forward_logic = forward_logic

    def set(self, speed):
        speed = max(-100, min(100, speed))
        self.DIR.value(self.forward_logic if speed > 0 else (1 - self.forward_logic))
        self.PWM.duty(int(abs(speed) / 100.0 * 1023.0))


M1 = Motor(18, 19, 1)
M2 = Motor(23, 2, 0)


class Servo:
    def __init__(self, pin):
        self.pin = PWM(Pin(pin, Pin.OUT), freq=50, duty=0)
        self.pin.deinit()
        self.pin.init()
        self.pin.freq(50)
        self.pin.duty(0)

    def angle(self, value):
        value = max(0, min(180, value))
        self.pin.duty(int(25.57 + ((value / 180.0) * 102.3)))

    def stop(self):
        self.pin.duty(0)


SV1 = Servo(4)
SV2 = Servo(15)

ADS7828_ADDR = 0x4A


def ADC(ch):
    i2c = I2C(0, scl=Pin(21), sda=Pin(22), freq=100000)
    i2c.writeto(
        ADS7828_ADDR,
        bytes([((0, 4, 1, 5, 2, 6, 3, 7)[ch] << 4) | 0x8C])
    )
    high, low = i2c.readfrom(ADS7828_ADDR, 2)
    return ((high << 8) | low) & 0x0FFF


_movement_speed = 100
_ref_l = 0
_ref_r = 0
_intersection_forward_time = 0.5


def _drive(action, speed):
    if action == "FORWARD":
        M1.set(speed)
        M2.set(speed)
    elif action == "BACKWARD":
        M1.set(-speed)
        M2.set(-speed)
    elif action == "TURN_LEFT":
        M1.set(0)
        M2.set(speed)
    elif action == "TURN_RIGHT":
        M1.set(speed)
        M2.set(0)
    elif action == "SPIN_LEFT":
        M1.set(-speed)
        M2.set(speed)
    elif action == "SPIN_RIGHT":
        M1.set(speed)
        M2.set(-speed)
    else:
        M1.set(0)
        M2.set(0)


def move(action, speed):
    global _movement_speed

    speed = abs(max(-100, min(100, speed)))
    _movement_speed = speed
    _drive(action, speed)


def uturn(direction, speed=None):
    # Compatibility with code generated by iBIT extension 1.1.4.
    if speed is None:
        speed = direction
        direction = "LEFT"

    speed = abs(max(-100, min(100, speed)))
    if direction == "RIGHT":
        action = "SPIN_RIGHT"
        sensor_channel = 1
        reference = _ref_r
    else:
        action = "SPIN_LEFT"
        sensor_channel = 0
        reference = _ref_l

    _drive(action, speed)

    if _line_detected(sensor_channel, reference):
        while _line_detected(sensor_channel, reference):
            sleep(0.001)

    while not _line_detected(sensor_channel, reference):
        sleep(0.001)

    _drive("STOP", 0)


def set_ref_l(value):
    global _ref_l
    _ref_l = value


def set_ref_r(value):
    global _ref_r
    _ref_r = value


def set_intersection_forward_time(seconds):
    global _intersection_forward_time
    _intersection_forward_time = max(0, seconds)


def _line_detected(channel, reference):
    return ADC(channel) <= reference


def _wait_for_intersection():
    while not (_line_detected(0, _ref_l) and _line_detected(1, _ref_r)):
        sleep(0.001)


def intersection(action, forward_time=None, speed=None):
    if forward_time is None:
        forward_time = _intersection_forward_time
    else:
        forward_time = max(0, forward_time)

    if speed is None:
        speed = _movement_speed
    else:
        speed = abs(max(-100, min(100, speed)))

    _wait_for_intersection()
    _drive("FORWARD", speed)
    sleep(forward_time)

    if action == "CROSS":
        return

    if action == "STOP":
        _drive("STOP", 0)
        return

    if action == "TURN_LEFT":
        _drive("SPIN_LEFT", speed)
        while not _line_detected(0, _ref_l):
            sleep(0.001)
    elif action == "TURN_RIGHT":
        _drive("SPIN_RIGHT", speed)
        while not _line_detected(1, _ref_r):
            sleep(0.001)

    _drive("STOP", 0)


def intersection_stop(speed=None):
    if speed is not None:
        speed = abs(max(-100, min(100, speed)))
        _drive("FORWARD", speed)

    _wait_for_intersection()
    _drive("STOP", 0)


class Gripper:
    def __init__(self):
        self.enabled = False
        self.grip_servo = SV1
        self.lift_servo = SV2
        self.positions = {
            "GRAB": 80,
            "RELEASE": 25,
            "UP": 10,
            "DOWN": 110
        }
        self.settle_time = 0.3

    def enable(self, enabled):
        self.enabled = bool(enabled)
        if not self.enabled:
            SV1.stop()
            SV2.stop()

    def set_ports(self, layout):
        if layout == "SWAPPED":
            self.grip_servo = SV2
            self.lift_servo = SV1
        else:
            self.grip_servo = SV1
            self.lift_servo = SV2

    def set_degree(self, position, degree):
        if position in self.positions:
            self.positions[position] = max(0, min(180, degree))

    def _move_to(self, position):
        if not self.enabled or position not in self.positions:
            return

        if position == "GRAB" or position == "RELEASE":
            self.grip_servo.angle(self.positions[position])
        else:
            self.lift_servo.angle(self.positions[position])
        sleep(self.settle_time)

    def control(self, action):
        if action == "PICK_UP":
            self._move_to("GRAB")
            self._move_to("UP")
        elif action == "PLACE_DOWN":
            self._move_to("DOWN")
            self._move_to("RELEASE")
        else:
            self._move_to(action)

    def home(self):
        self._move_to("RELEASE")
        self._move_to("UP")


GripperX = Gripper()
